name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  pod-trunk-push:
    runs-on: macOS-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.2"
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push --allow-warnings
